#!/usr/bin/env node

const fs = require('fs')
const path = require('path')

// reset meta json
fs.writeFileSync(path.join(__dirname, '../meta.json'), '[]')
// remove all files from uploads
fs.readdirSync(path.join(__dirname, '../uploads')).forEach(file => {
  // dont remove dotfiles aka: .gitkeep
  if(file[0] !== '.') {
    fs.unlinkSync(path.join(__dirname, '../uploads', file))
  }
})